# Generated by Django 5.0.7 on 2024-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_categori_women_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categori',
            new_name='Category',
        ),
    ]
